### ISSUE TITLE
Docs update? Linux compiler should support C++11 ==> C++14

### ISSUE THREAD

**Issue by lmmx** [ryancole/hdf5.node#12]
Hi, just got a bit confused by the installation docs until I looked at what `binding.gyp` was doing, as it's a bit contradictory. [They say](http://rycole.com/hdf5.node/doc/install-setup.html)

> The code requires a gcc compiler supporting C++11 for linux.

I had pre-C++14 `g++-4.8`, that came with my distro (Ub 14.04-based). I've now updated to the current [C++14-supporting] `g++-4.9` after the `npm install` failed with an error telling me about

      g++: error: unrecognized command line option ‘-std=c++14’

If I've got the wrong idea then apologies, but I might have cottoned on a bit sooner had the docs said "you need a compiler supporting C++14". Is it a typo // needs updating to reflect changes in the package?

Again, I might be wrong, but [from looking at this](https://github.com/ryancole/hdf5.node/blob/master/binding.gyp#L260) are Macs also using C++14 compilers (so should the same edit be made to the OS X installation instructions)?

**Comment by rimmartin** [comment]
You can change to -std=c++11 for a build

It is a bit confusing because that was an experiment to see if it would compile with c++14 and I was looking to experiment with some code.  But the current code should build with c++11.

Yet if you have 4.9 it should build with -std=c++14 as well.

**Comment by lmmx** [comment]
Ah, ok! I thought that might have worked but... felt like it made more sense to fix the error message rather than edit the `binding.gyp` on that hunch. Will leave it with you then :+1:

**Comment by rimmartin** [comment]
I'm working on producing prebuilts and will publish some updates.
