### ISSUE TITLE
bindings.gyp line endings

### ISSUE THREAD

**Issue by mrfitz42** [ryancole/hdf5.node#15]
Trying to install on linux with node v0.12.7 and npm v2.11.3
Ran 'npm install hdf5@0.0.20 --fallback-to-build'
Fails on line 1 of binding.gyp.  Based on the local clone, it seems binding.gyp has eol=crlf instead of text=auto.  Changing the local binding.gyp with dos2unix lets it compile, but there is not a version 0.0.20 branch or tag to use.

**Comment by rimmartin** [comment]
Hi
```
npm install hdf5@0.0.20 --build-from-source
```
worked for me on ubuntu; I'l  try tomorrow on a windows box at work. I don't see any eol=crlf or on linux those show as ^M in binding.gyp. 

0.0.20 as to make prebuilts with hdf5-1.8.15-patch1. Otherwise it is the same as 0.0.19 as far as source code.

Which version of the native hdf5 library are you working with?

**Comment by mrfitz42** [comment]
Hi,
Sorry if this is a setup issue, but I'm new to git, npm, and node. 
I'm running on a Redhat 6.7 VM and have hdf5-1.8.16 installed.

**Comment by rimmartin** [comment]
May I ask what locks you pre nodejs v4.2.1?

**Comment by mrfitz42** [comment]
Legacy installation.  Need to stay pre-ES6.

**Comment by rimmartin** [comment]
ah, let me know if you'll need changes in the 0.0.19 branch; it is the same as 0.0.20

**Comment by mrfitz42** [comment]
Right now I just need to figure out a way to force the 'npm install ...' to download binding.gyp with lf instead of crlf.  I'd change it after download, but when the install fails the files are deleted.

**Comment by rimmartin** [comment]
https://github.com/ryancole/hdf5.node/blob/v0.0.19/binding.gyp
has crlf's in it?

have you tried 
```
npm install hdf5@0.0.19 --build-from-source
```
I did it with 
```
npm install hdf5@0.0.20 --build-from-source
```
and checked for ^M and saw none

**Comment by rimmartin** [comment]
if you vi the binding.gyp if there is a crlf it shows up as ^M

**Comment by rimmartin** [comment]
what does the error look like?

**Comment by rimmartin** [comment]
your machine is  32 or 64 bit?

**Comment by mrfitz42** [comment]
> node-pre-gyp install --fallback-to-build

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2736, in Load
    variables, includes, depth, check, True)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 386, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 238, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-573.8.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=$NODE_PATH/node_modules/hdf5/lib/binding/hdf5.node" "--module_name=hdf5" "--module_path=$NODE_PATH/node_modules/hdf5/lib/binding" "--python=/usr/bin/python2"

**Comment by mrfitz42** [comment]
64 bit

**Comment by mrfitz42** [comment]
My bad, I should have searched for "syntax error on binding.gyp line 1".  First result tells me it's a python version problem.  This VM has Python 2.6.6, node-gyp wants 2.7.  Now to get python 2.7 installed.

**Comment by mrfitz42** [comment]
That did it.  'npm install hdf5@0.0.19 --build-from-source --python=$path_to_python2.7' worked.
