### ISSUE TITLE
basic file creation / dataset issues

### ISSUE THREAD

**Issue by dasantonym** [ryancole/hdf5.node#7]
i was not able to create a new hdf5 file (osx 10.10.3, node 0.12.0, compiled with gcc-4.9). so i used your example code in http://rycole.com/hdf5.node/tut/dataset-tutorial.html

i am getting the same errors as with my own previous tries. i am not sure if this due to my limited knowledge of hdf5 but i'll now have to read up on this anyway. maybe the output is really an issue and of interest to you:

```shell
/usr/local/bin/node index.js
'hdf5 exports'
flags 2
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
  #000: H5Pocpl.c line 1303 in H5Pset_deflate(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #001: H5Pint.c line 3381 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Unable to register new atom
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
  #000: H5D.c line 165 in H5Dcreate2(): not a location ID
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
id 16777216
/Users/anton/WebstormProjects/hdf5-test/index.js:15
h5lt.makeDataset(group.id, 'Refractive Index', buffer);
     ^
SyntaxError: failed to make dataset
    at SyntaxError (native)
    at Object.<anonymous> (/Users/anton/WebstormProjects/hdf5-test/index.js:15:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Process finished with exit code 1
```

**Comment by rimmartin** [comment]
Ok, I tested an hdf5-test user -like project on Ubuntu just now.  Heading to work to try this on mac.

Are permissions  different on mac? to folder such as /tmp?

**Comment by dasantonym** [comment]
i also tried the local repo path to no avail. the file definitely gets created for both tmp and repo path and fails with the same error.  

thanks for the quick response, i'll have a go on ubuntu later on as well.

**Comment by rimmartin** [comment]
ok, I repeated the test on a mac 10.7 node v0.12 gcc-4.9 and couldn't repeat the error with what it pulls from git.  Didn't open the h5 with hdfview but it's size is 2184 bytes as it is on ubuntu.

I wonder if the group even got made.  Maybe check if the group.id is 0 or greater.

You r way of setting up a dependent project?  For this test I made a node_modules sub folder and put a sym link to hdf5.node in it.

You may have done similar because the hdf5.node/index.js appears to be working and hdf5/lib/globals.js is being found

**Comment by rimmartin** [comment]
my current test script:
```bash
#!/bin/bash

function pause(){
   read -n 1 -p "Press any key to continue..."
}

export HDF5_HOME=/home/roger/NodeProjects/hdf5
export NODE_HOME=/home/roger/Software/node-v0.12.0/dist
export PATH=/home/roger/Software/gcc/dist/bin:$NODE_HOME/bin:$PATH
export LD_LIBRARY_PATH=/home/roger/Software/gcc/dist/lib64:/home/roger/NetBeansProjects/zlib/lib:$HDF5_HOME/lib:$LD_LIBRARY_PATH

#export HDF5_PLUGIN_PATH=/home/roger/NodeProjects/HDF5Plugin

node ./index.js #2> /dev/null

node --version
node -e "console.log(process.versions.v8)"

pause
```

and index.js
```javascript
var hdf5 = require('hdf5').hdf5;
var h5lt = require('hdf5').h5lt;

var Access = require('hdf5/lib/globals').Access;

var file = new hdf5.File('/tmp/foo.h5', Access.ACC_TRUNC);

var group=file.createGroup('pmc');
var buffer=new Float64Array(5);
buffer[0]=1.0;
buffer[1]=2.0;
buffer[2]=3.0;
buffer[3]=4.0;
buffer[4]=5.0;
h5lt.makeDataset(group.id, 'Refractive Index', buffer);
var readBuffer=h5lt.readDataset(group.id, 'Refractive Index');
```

**Comment by rimmartin** [comment]
on mac DYLD_LIBRARY_PATH instead of LD_LIBRARY_PATH

**Comment by dasantonym** [comment]
ah i see, i think it really might just be a problem with the env vars (library path especially). i'll give it a shot tonight and report back. thanks a ton for the help!

**Comment by dasantonym** [comment]
took me a while to check it out, sorry, but good news. it works and it was the incomplete environment vars. i'll now be happily digging deeper into this subject. thanks for all the help and especially for this module in the first place.
